### ISSUE TITLE
Backend: Content itself,votes and comments can not be reached even the contents belongs to a group that the user follows.

### ISSUE THREAD

**Issue by emreshome** [bounswe/bounswe2017group6#357] opened 2017-11-29 00:16 UTC
## About

In the following case, I faced with a bug:
- I logged in with "admin" and easily accessed to grup surup's contents' votes and comments.
However, when I logged in as "emre", even if I am following grup surup, I was not be able to reach the comments and votes of the grup surup's contents.

**Comment by yhkalayci** [comment] 2017-11-29 10:32
The cause of this problem is that owner of the contents of the grup surup's is admin and admin is not a regular user.

**Comment by yhkalayci** [comment] 2017-11-29 10:34
Also, please make sure that for all created contents, groups, comments and votes, owner of these type of models is set.

**Comment by yhkalayci** [comment] 2017-11-29 12:24
I am closing this issue since this is related to the current status of the database. If you face this problem again please let me know to solve it from database.

**Closed as completed by yhkalayci** 2017-11-29 12:24 UTC
Labels: bug, backend
